SSD13xx performance: some direct screen buffer writer methods
nanoframework/nanoFramework.IoT.Device pull request #223
Opened 2022-01-06 14:08 UTC by SandorDobos

## Description
I added some methods which allow faster display of bitmaps and fast partial screen clearing.

All existing ```Draw*()``` methods (including ```DrawBitmap()```)  use the ```DrawPixel()``` method 
to write anything into internal buffer which going to be transfered to device on ```Display()``` call.
Having bitmaps on hand this method is very slow.

Assuming the bitmaps are in appropriate format (see SSD13xx docs for "GDDRAM" and "Horizontal addressing mode")
the new ```DrawDirectAligned``` method simply copies the incoming byte array to appropriate place in internal buffer
which results is ~100 times faster display speed.
There are constraints: no bit operations occure with existing buffer data, so the "y" coordinate and the bitmap height must be byte aligned!

Same constraints apply to new ```ClearDirectAligned``` method which allow partial (rectangle) screen clearing 
by setting appropriate internal buffer bytes to 0x00. This is also ~100 times faster than doing same with existing ```DrawFilledRectangle``` method.
 

## Motivation and Context
Using bitmaps actively the existing methods were unacceptable slow.

## How Has This Been Tested?
I am using this implementation in my own project.

## Types of changes

- [x] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (work on Unit Tests, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-01-10 09:56 UTC, Ellerbach commented on devices/Ssd13xx/Ssd13xx.cs
> +            for (int i=0; i<dataHeightInBytes; i++)
please use `ctrl + k + d` in Visual Studio to have a proper alignment of the code ;-)

2022-01-10 09:58 UTC, Ellerbach commented on devices/Ssd13xx/Ssd13xx.cs
> +        /// <param name="buffer">Data to copy.</param>
please with the size the buffer needs to have to make it clear. In short, height * width / 8.

2022-01-10 10:00 UTC, Ellerbach reviewed
Few comments. Looks good!
Can you add as well a code snippet in the Readme or in the sample on how to use the 2 functions.

2022-01-11 12:51 UTC, josesimoes commented
@SandorDobos can you please address @Ellerbach  comment above so we can have this merged?

2022-01-16 20:28 UTC, SandorDobos commented
@josesimoes , @Ellerbach Done :)

2022-01-16 21:00 UTC, josesimoes requested changes

2022-01-17 08:19 UTC, SandorDobos commented on devices/Ssd13xx/README.md
> +If you wish to update big part of screen (e.g. drawing images or shapes instead of printing text)
I would say that the lines above line 40 contain importand developer information about how other methods work (they are just functional wrappers around ````DrawPixel````). This information has a value without the new methods and their explanation. I reworded the whole section, hope you will like this version :)

2022-01-17 08:25 UTC, josesimoes commented on devices/Ssd13xx/README.md
> +If you wish to update big part of screen (e.g. drawing images or shapes instead of printing text)
From a developer looking into the inner bits of the library or trying to understand deeper, I agree. For a "regular" _just_ wanting to use the library, those are spurious.

That's why they belong in the PR or in the code comments. To help on those situation and for developers diving deep in the code.

It's better now. Thanks!

2022-01-17 08:26 UTC, merged