Adding support for SSD1306 OLED display with 7-pin I2C/SPI
nanoframework/nanoFramework.IoT.Device pull request #443
Opened 2022-06-11 12:55 UTC by devdotnetorg

The existing code only supports SSD1306 display with 4-pin.
But there is a version with 7-pin I2C/SPI. For this version it is necessary to initialize the pin - RES.

## Description
Adding support for SSD1306 OLED display with 7-pin I2C/SPI for only I2C.

Description will be available on June 13-17 at the link - [post (rus)](https://habr.com/ru/company/timeweb/blog/669700/).

## Motivation and Context

- Fixes/Closes/Resolves nanoFramework/Home#NNNN

## How Has This Been Tested?

- VS 2019 Community Edition on Windows 10
- ESP-WROOM-32

## Screenshots
[![IMAGE_ALT](https://devdotnet.org/wp-content/media/new-nf-lcd-wifi-title.jpg)](https://devdotnet.org/wp-content/media/new-nf-lcd-wifi-title.jpg)

## Types of changes

- [x] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [x] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [x] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (add new Unit Test(s) or improved existing one(s), has no impact on code or features)
- [x] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [x] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/master/CONTRIBUTING.md) document.
- [ ] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).
- [ ] I have added new tests to cover my changes.

2022-06-11 12:56 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/nanoframework/nanoFramework.IoT.Device?pullRequest=443) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/nanoframework/nanoFramework.IoT.Device?pullRequest=443) before we can accept your contribution.<br/><br/>:x: devdotnetorg [sign now](https://cla.dotnetfoundation.org/nanoframework/nanoFramework.IoT.Device?pullRequest=443)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/nanoframework/nanoFramework.IoT.Device?pullRequest=443) it.</sub>

2022-06-12 13:37 UTC, Ellerbach requested changes
Please adjust the GpioController to the proper pattern. And it will be good!

2022-06-12 13:37 UTC, Ellerbach commented on devices/Ssd13xx/Ssd1306.cs
> +        public Ssd1306(I2cDevice i2cDevice, int rstPinNumber) : base(i2cDevice, rstPinNumber)
If you pass a pin number, you need to allow the possibility to pass the GPIO controller and also add the shouldDispose boolean to dispose it or not at the end. You'll find the pattern in other bindings.

2022-06-12 13:37 UTC, Ellerbach commented on devices/Ssd13xx/Ssd13xx.cs
> +            var s_GpioController = new GpioController();
As pointed, this is not the correct pattern. Please use the proper pattern.
Also, you need to check that rstPinNumber is valid.

2022-06-14 14:48 UTC, josesimoes commented
@devdotnetorg any chance you can resume work on this? It can get a bit behind the develop branch and it's more work... 😉

2022-06-14 20:50 UTC, devdotnetorg commented
@josesimoes Yes, I will finish the work, but only at the end of this week.

2022-07-27 12:59 UTC, Ellerbach commented
@devdotnetorg as we're now a bit more than the end of the week you mentioned, any chance to move it forward? Thanks!

2022-07-29 23:10 UTC, devdotnetorg commented
@Ellerbach I will likely close the change-ssd13xx branch and create a new one to avoid merge issues

2022-08-22 11:34 UTC, Ellerbach commented
@devdotnetorg are you still working on this? Any help needed?

2022-08-23 23:41 UTC, devdotnetorg commented
@Ellerbach I created a theme [Adding support for SSD1306 OLED display with 7-pin I2C/SPI V2.](https://github.com/nanoframework/nanoFramework.IoT.Device/pull/550)

2022-08-23 23:41 UTC, closed without merging